# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "win2012r2"

	config.vm.communicator = "winrm"

	config.vm.hostname = 'sqlserverdevmachine'

	# forward RDP, WINRS ans SQL Server ports
	config.vm.network :forwarded_port, guest: 3389, host: 3377, id: "rdp", auto_correct: false
	config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
	
	# uncomment this if you have no sql server on your host and want to be able to use localhost as the data source.
	# config.vm.network :forwarded_port, guest: 1433, host: 1433, id: "mssqlserver", auto_correct: true

	config.windows.set_work_network = true

	config.vm.provision :shell, path: "../scripts/Install-Chocolatey.ps1"
	config.vm.provision :shell, inline: '[Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Chocolatey\bin", "Machine")'

	config.vm.provision :shell, path: "Scripts/Install-Apps.ps1"
	
	config.vm.provision :shell, path: "../scripts/Enable-RDP.ps1"
	config.vm.provision :shell, path: "../scripts/Modify-Firewall.ps1"

	config.vm.provision :shell, path: "../scripts/Set-License-Key.ps1"

	config.vm.provider "virtualbox" do |v|
		v.gui = false
		v.name = "sqlserverdevmachine"
		v.cpus = 1
		v.memory = 4096
	end
end