# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "box-cutter/ubuntu1404-desktop"	
	config.vm.provision :shell, path: "Scripts/Install-Node.sh"
	config.vm.provision :shell, path: "Scripts/Install-Mono.sh"
	config.vm.provision :shell, path: "Scripts/Install-libuv.sh"
	config.vm.provision :shell, path: "Scripts/Install-DNVM.sh"

	#config.vm.provision :shell, path: "Scripts/Reset-npm-path.sh"
	config.vm.provision :shell, path: "Scripts/Install-Yeoman.sh"
	config.vm.provision :shell, path: "Scripts/Install-Atom.sh"

	config.vm.provider "virtualbox" do |v|
		v.name = "aspnet5-lab-machine"
		v.gui = true
		v.cpus = 2
		v.memory = 4096
	end
end
