# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "win8"

	config.vm.communicator = "winrm"

	config.vm.hostname = "devmachine"

	# forward RDP and WINRS ports
	config.vm.network :forwarded_port, guest: 3389, host: 3378, id: "rdp", auto_correct: false
	config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
	config.vm.network :forwarded_port, guest: 80, host: 8080, id: "localhost", auto_correct: false

	config.windows.set_work_network = true
	
	config.vm.provision :shell, path: "../scripts/Install-Chocolatey.ps1"

	config.vm.provision :shell, path: "Scripts/Install-Apps.ps1"
	
	# Different powershell when the box is server 2012 or windows 8
	#config.vm.provision :shell, path: "../scripts/Install-IIS.ps1"
	config.vm.provision :shell, path: "../scripts/Install-IIS-for-Win8.ps1"

	config.vm.provision :shell, path: "../scripts/Set-License-Key.ps1"

	config.vm.provider "virtualbox" do |v|
		v.name = "devmachine"
		v.gui = true
		v.cpus = 2
		v.memory = 8192
		v.customize ["setextradata", :id, "CustomVideoMode1", "1600x900x32"]
	end
end